# Generated by Django 2.0.13 on 2019-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0002_auto_20191125_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinfo',
            name='cid',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='mylearninginfo',
            name='categoryid',
            field=models.CharField(max_length=13),
        ),
    ]
