# Generated by Django 2.0.13 on 2019-12-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0004_auto_20191204_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryinfo',
            name='cid',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mylearninginfo',
            name='categoryid',
            field=models.CharField(max_length=15),
        ),
    ]
