# Generated by Django 2.0.13 on 2019-12-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0005_auto_20191204_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylearninginfo',
            name='categoryname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
